### PR TITLE
Add breadcrumb component for Sketch

### PR DESCRIPTION
**Pull request by pglevy**
Guidance not complete yet. This is work in progress.

Notes and questions:
1. Does this cover the options you'd want to include?
2. I tried a group with some pinned elements for the truncation. It's not super-flexible, so let me know if you think this is helpful or not.
3. It looks like the usa-link--light text style was updated with a fill color, so for now I just unchecked that to get the default style. (Screenshot below.)

image

### CODE REVIEW

**Comment by mejiaj** [comment]
Looks like everything we have so far is in here.

**Comment by pglevy** [comment]
added default sketch symbol

**Comment by pglevy** [comment]
@thisisdano , I retitled this pull request to cover only the Sketch update so we can nail that down first (though there is an earlier XD commit in there). I think I've got the symbols and links to the library set up correctly, but feel free to make changes as you see fit. A couple notes:

- I did end up updating the links/usa-link--light style to correctly reflect the documentation. So this may impact some other components in the Sketch file.
- For the inverse, I created the example using overrides with the default symbol instead of creating a new one. I wasn't sure what approach you preferred there.

Marking as ready for review...

**Review by thisisdano — APPROVED** [review]

**Comment by thisisdano** [comment]
Closing in favor of https://github.com/uswds/uswds-for-designers/pull/77
Ended up removing both the truncation and the inverse options, just to keep things simple. We won't be including the inverse styling as a code example, so it make sense to remove it from here as well. And the truncation option can be adequately mimicked with plain text.

**Pull request closed without merging**
