### PR TITLE
Adding Sketch palette and color files for the WDS color scheme.

### LINKED ISSUE #23: Create a color palette file for Sketch
I don't _think_ there's a native way to add a color palette in Sketch, but it would be helpful to provide the color palette as a .clr file for Sketch users a la: https://medium.com/@san_toki/import-the-material-design-color-palette-into-sketch-3-e31caf2f6a12#.xbadr56sz

### PR DESCRIPTION
**Pull request by juliasolorzano**
This pull request adds the Sketch files @rtwell created to use the WDS in your Sketch files.

Nice work, @rtwell!

//cc @ericadeahl 

Fixes #23

### CODE REVIEW

**Comment by rtwell** [comment]
one last comment—i'm not sure why we are making separate documents for type
and color. it would be easier, particularly for designers, to just get one
file with 2 art boards.

**Comment by juliasolorzano** [comment]
Cool - maybe we open a new issue for this to noodle on?

**Comment by ericadeahl** [comment]
@juliaelman We decided to add color swatches into the Sketch sticker sheet. This is ready to go: we should add the WDS.sketchpalette file into the Colors folder, but discard the WDS_colors.sketch file.

**Comment by juliasolorzano** [comment]
@ericadeahl sounds good! I'll close this pull request and thanks for following up 😄

**Pull request closed without merging**
