### PR TITLE
Added color palette instructions to the README

### PR DESCRIPTION
**Pull request by kategarklavs**
Per Erica's request, I made some tiny edits to these instructions & added them to the README.

### CODE REVIEW

**Comment by ericadeahl** [comment]
Cool, thanks @kategarklavs!

Makes sense to add the instructions where you have them. 

Two small comments:
- Folks have a couple options for working with the color palette — they can work with the color swatches included in the AI and Sketch sticker sheet files, and/or they can install the ASE or Sketch Palette files. In that intro sentence, perhaps we should point out that the color palettes are available both ways (?)
- I would change the last Sketch bullet point to "Navigate to WDS.sketchpalette to add the palette."

**Comment by juliasolorzano** [comment]
@kategarklavs just fixed the build error that was showing up. All should be well now 😄

**Comment by juliasolorzano** [comment]
@ericadeahl @kategarklavs hello friends! I just merged in those changes, but wanted to know if you all wanted one more 👀  before merging this in. Feel free to merge away if y'all think it's good to go! 😄

**Comment by ericadeahl** [comment]
@juliaelman All looks good, thank you! @kategarklavs Looks like this now includes the edits from your second PR. I'm going to go ahead and merge.

**Comment by kategarklavs** [comment]
@ericadeahl Aye aye!

**Pull request merged**
