### PR TITLE
consistency-updates

### PR DESCRIPTION
**Pull request by cathrowe**
- Everything is in whole pixels — no decimals on sizes or placement
- Consistent heights for all forms that match what’s live on the site
- Buttons, checkboxes, and radio buttons utilize nested symbols for
more flexibility
- Palette swatch fills, Document Colors, Shared Styles, and hex codes
are consistent
- Symbols take advantage of resizing
- Minor adjustments to footers to bring them more in line with what’s
live on the site
- Typography spacing measurements reflect spacing in Sketch
- Artboard sizes updated to ensure Sketch columns are sized correctly
and positioned on whole pixels
- Updated layer and symbol names
- Lines in tables are now rectangles to allow for more accurate spacing
- Sticker sheet text is more consistent, easier to read when zoomed
out, and disconnected from header styles
- Label background fills use radius for the rounded corners so they can
be resized
- Borderless table has new title background fill to match live site
- Used Symbol Organizer plugin to clean up Symbols page
(https://github.com/sonburn/symbol-organizer)
- Header styles renamed to “Serif” and “Sans” for greater flexibility
to re-use and customize
- Lists of fonts included with each pairing updated to reflect usage
- Desktop and Mobile grids are aligned with Sketch grid

### CODE REVIEW

**Comment by bradnunnally** [comment]
@yowill I won't have time to review these updates and apply them to the other sticker sheets this sprint. How would you like to handle this issue? It should be high priority for the next sprint.

**Comment by bradnunnally** [comment]
Recent updates to all the sticker sheets include 

- Added the header components
- Fixed type issues in the headers and table
- General clean up of text - there are several areas where the text is broken up into several objects because of poor importing. E.g. An official website of the United States Government might be 3 separate text objects and they will need to be combined into one.

**Comment by bradnunnally** [comment]
@yowill Moving this back to the backlog because it's not part of this sprint and I thought it was.

**Comment by maya** [comment]
@thisisdano just realized this has been open for a while.

**Comment by maya** [comment]
Hi @cathrowe, thanks so much for this PR. Our team is just seeing this and impressed with this work! We've made some changes to the Sketch file since this was created so may have to look more closely at seeing what we can bring in from this.

We'll review this with our team and see how it fits on our roadmap. Stay tuned!

**Comment by maya** [comment]
Consider using this as a baseline for our new sticker sheet (post-2.0).

**Comment by maya** [comment]
Included some of this in #54, thanks for your help, @cathrowe!

**Pull request closed without merging**
