### PR TITLE
Update design assets

### LINKED ISSUE #53: Update assets to USWDS 2.0
We'll need tp update the USWDS Sketch sticker sheet to better support USWDS 2.0

### PR DESCRIPTION
**Pull request by thisisdano**
A brand new set of design files for Sketch. 💎 
This builds upon a lot of the smart ideas in https://github.com/uswds/uswds-for-designers/pull/40 and adds a few new tricks of its own. 🚀 

- added documentation about use and installation to readme
- better use of nested symbols
- consistent resizing of symbols
- cleaner organization
- tidied up styles
- improved consistency
- introduced USWDS Block: a library-based symbol sync technique
- **[beta]** introduced customizable avatars based on an original library created by Pablo Stanley ([link](http://avataaars.com)) further customized by @cmajel and @18F
- **[beta]** integrated handoff symbols based on work from @linziberry and @soffes ([link](https://medium.com/tap-to-dismiss/constraint-layout-for-designers-3c665cb4d074))

- - -

- also added two new color reference docs: a complete collection of all USWDS 2.0 system, theme, and state colors, and a compact color wheel for demonstration purposes
- removed all the currently unused gulp dev baggage
- updated the license and added new versions of the typefaces
- moved all the old assets to an `old` folder 👴 

- - -
Fixes #53 
Supercedes #40 (thank you @cathrowe!)

### CODE REVIEW

**Comment by maya** [comment]
Does this work supersede #40?

**Comment by thisisdano** [comment]
Yes, but I will take a look at that work and see if there's anything I can implement in the new system. Also, I clarified this issue to make it clear it's a WIP. Don't merge yet.

**Comment by thisisdano** [comment]
De-WIPped! 🍨

**Comment by maya** [comment]
Is the intention that the default font is Public Sans, not Source Sans Pro and Merriweather?

A few instances where the text breaks:
Screen Shot 2019-04-03 at 9 58 12 AM

Screen Shot 2019-04-03 at 10 04 11 AM

Where are the page templates? Or are we not including them?

**Comment by maya** [comment]
Maybe it's b/c I don have the most recent version of Public Sans... will try to uninstall and reinstall.

**Comment by maya** [comment]
Nope, still seeing the same issue after uninstalling and reinstalling Public Sans from the font files provided.

**Comment by thisisdano** [comment]
Hm — I don't see those breaks but I can try and fix.
Also, I didn't have page templates in the file I was working from... I wonder why?

**Comment by thisisdano** [comment]
Also, I left a note in the `_How to use the stickersheets` but I've kept everything in Public Sans rn because of some of the complexity around font normalization in Sketch

**Comment by thisisdano** [comment]
@maya I've made some progress toward font switching, but we won't have a complete solution just yet. Once you can give it another once-over for weird button stuff, it should be ready to merge.

**Review by maya — APPROVED** [review]
LGTM 🚀

**Comment by maya** [comment]
@thisisdano how are the zip files generated for https://v2.designsystem.digital.gov/download/ again?

**Comment by maya** [comment]
I see they live here: https://github.com/uswds/uswds-site/tree/v2/files and need to be updated. Are we still providing the other design files or are they being deprecated?

**Comment by thisisdano** [comment]
I'll have to manually make the zip files and add them to `uswds-site` — the other design files are still in the 1.x state. I don't think they're officially deprecated yet, but I don't have a good sense of priorities yet when it comes to formats other than Sketch.

**Pull request merged**
